name: GKI Kernel Build For AVD

on:
  workflow_call:
    inputs:
      version_name:
        required: true
        type: string
        description: >
          With SUBLEVEL of kernel,
          for example: android12-5.10.66
      arch:
        required: true
        type: string
        description: >
          Build arch: aarch64/x86_64
      debug:
        required: false
        type: boolean
        default: true
      manifest_name:
        required: false
        type: string
        description: >
          Local repo manifest xml path,
          typically for AVD kernel build.
    secrets:
      BOOT_SIGN_KEY:
        required: false
      CHAT_ID:
        required: false
      BOT_TOKEN:
        required: false
      MESSAGE_THREAD_ID:
        required: false

jobs:
  build:
    name: Build ${{ inputs.version_name }}
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@v4
        with:
          path: KernelSU
          fetch-depth: 0

      - name: Setup need_upload
        id: need_upload
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            echo "UPLOAD=true" >> $GITHUB_OUTPUT
          else
            echo "UPLOAD=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup kernel source
        run: |
          echo "Free space:"
          df -h
          cd $GITHUB_WORKSPACE
          sudo apt-get install repo python3 -y
          mkdir android-kernel && cd android-kernel
          repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -m "$GITHUB_WORKSPACE/KernelSU/.github/manifests/${{ inputs.manifest_name }}" --repo-rev=v2.16
          repo --version
          repo --trace sync -c -j$(nproc --all) --no-tags
          df -h
      
      - name: Setup, Build and Package Kernel
        run: |
          python3 $GITHUB_WORKSPACE/KernelSU/.github/scripts/kernel_build.py \
            --workspace "$GITHUB_WORKSPACE" \
            --kernel-source-path "$GITHUB_WORKSPACE/android-kernel" \
            --kernel-version "${{ inputs.version_name }}" \
            --arch "${{ inputs.arch }}" \
            --buildtype avd \
            $([[ ${{ inputs.debug }} == 'true' ]] && echo '--debug') \
            --manager-sign-size "${{ vars.EXPECTED_SIZE || '' }}" \
            --manager-sign-hash "${{ vars.EXPECTED_HASH || '' }}" \
            --github-env-file "$GITHUB_ENV"

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ inputs.arch }}-avd-${{ inputs.version_name }}-${{ env.kernelsu_version }}
          path: ./KernelSUBuild/avd/*Image*

      # - name: Upload dist
      #   uses: actions/upload-artifact@v5
      #   with:
      #     name: dist-${{ inputs.arch }}_${{ inputs.version_name }}_${{ env.kernelsu_version }}
      #     path: |
      #       ./KernelSUBuild/avd/*
      #       !./KernelSUBuild/avd/vmlinux*

